import type { Metadata } from "next";
import { Advent_Pro, Glory } from "next/font/google";
import "./globals.css";

const glory = Glory({ subsets: ["latin"] });

const adventPro = Advent_Pro({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OnTheWay",
  description: "Generated by OnTheWay",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={glory.className}>{children}</body>
    </html>
  );
}
