"use client"

// import type { Metadata } from "next";
import { Advent_Pro, Glory } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const glory = Glory({ subsets: ["latin"] });
const adventPro = Advent_Pro({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "OnTheWay",
//   description: "Generated by OnTheWay",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={glory.className}>
        {children}
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
